FormBuilder/Accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("signup/",views.signup_view,name = "signup"),
    path("login/",views.login_view,name = "login"),
    path("logout/",views.logout_view,name = "logout"),
]

FormBuilder/FormBuilder/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('Surveys.urls')),
    path('accounts/', include('Accounts.urls')),
    path('',views.landingPage, name = "landingPage"),
    path('home/',views.home, name="list")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FormBuilder/Surveys/urls.py
from django.urls import path
from . import views

app_name = "surveys" 

urlpatterns = [
    path('<int:survey_id>/', views.fetchSurvey),
    path('create/', views.createSurvey, name = "create"),
    path('stats/<int:survey_id>/', views.viewStats),
]

FormBuilder/templates/errorPage.html
<html>
    <title> update page </title>

    <body> 
        <h1> {{message}} </h1>
            <h3> <a href = {% url 'list' %}> Homepage </a> </h3> 
    </body>

</html>

FormBuilder/templates/home.html
<html>
    <title> Home Page</title>
    <body>

        <h1> welcome to Blogs </h1>
            <h2> user : {{user.first_name}} {{user.last_name}}</h2>

            <form method="POST" action = {% url 'accounts:logout' %}>
                {%csrf_token%}
                <input type="submit" value="logout"> 
            </form>
            <h3> <a href = {% url 'surveys:create' %}> Create a new survey </a> </h3>
        <ul>
            {% for item in surveyList%}
                <li> 
                    <a href = "/survey/{{item.id}}"> {{item.title}}</a> 
                    <a href = "/survey/stats/{{item.id}}">Statistics</a>
                </li>
            {% endfor %}
        </ul>

    </body>
</html>

FormBuilder/templates/landingPage.html
<html>
    <title> Home Page</title>
    <body>

            <h3> <a href = {% url 'accounts:login' %}> Login </a> </h3> 
            <h3> <a href = {% url 'accounts:signup' %}> Signup </a> </h3>
       

    </body>
</html>